# fly.toml app configuration file generated for mlmpk-cool-shadow-1738 on 2025-10-13T13:43:37+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mlmpk-cool-shadow-1738'
primary_region = 'iad'

[build]

[env]
  HOSTNAME = '0.0.0.0'
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
